SELECT DISTINCT PARTSUPP.PS_PARTKEY, PARTSUPP.PS_SUPPKEY
FROM PARTSUPP, PART, SUPPLIER
WHERE  
PARTSUPP.PS_PARTKEY = PART.P_PARTKEY AND
PART.P_MFGR = 'Manufacturer#1' AND
PART.P_BRAND = 'Brand#13' AND
PARTSUPP.PS_SUPPKEY = SUPPLIER.S_SUPPKEY AND
SUPPLIER.S_ACCTBAL > 2000 AND
PARTSUPP.PS_SUPPLYCOST > 500;
