SELECT DISTINCT LINEITEM.L_LINENUMBER, NATION.N_NATIONKEY
FROM ORDERS, LINEITEM, CUSTOMER, NATION
WHERE ORDERS.O_CUSTKEY=CUSTOMER.C_CUSTKEY AND 
ORDERS.O_ORDERKEY = LINEITEM.L_ORDERKEY AND
LINEITEM.L_COMMITDATE=LINEITEM.L_RECEIPTDATE AND
LINEITEM.L_LINESTATUS = 'O' AND
NATION.N_NATIONKEY = CUSTOMER.C_NATIONKEY;