CREATE STATISTICS PART_P_PARTKEY  
    ON PART(P_PARTKEY) 
WHERE PART.P_MFGR='Manufacturer#1'; 

CREATE STATISTICS PART_P_RETAILPRICE  
    ON PART(P_RETAILPRICE) 
WHERE PART.P_MFGR='Manufacturer#1'; 

CREATE STATISTICS PART_ALL  
    ON PART(P_PARTKEY,P_RETAILPRICE) 
WHERE PART.P_MFGR='Manufacturer#1'; 