SELECT DISTINCT LINEITEM.L_ORDERKEY, LINEITEM.L_LINENUMBER, PART.P_PARTKEY
FROM LINEITEM, ORDERS, PART
WHERE  
LINEITEM.L_RETURNFLAG = 'N' AND
LINEITEM.L_LINESTATUS = 'O' AND
LINEITEM.L_SHIPINSTRUCT = 'TAKE BACK RETURN' AND
LINEITEM.L_SHIPDATE=LINEITEM.L_COMMITDATE AND
LINEITEM.L_ORDERKEY = ORDERS.O_ORDERKEY AND
LINEITEM.L_PARTKEY = PART.P_PARTKEY AND
PART.P_MFGR = 'Manufacturer#1';
