CREATE STATISTICS LINEITEM_L_ORDERKEY
    ON LINEITEM(L_ORDERKEY) 
WHERE LINEITEM.L_RETURNFLAG = 'N' AND
LINEITEM.L_LINESTATUS = 'O' AND
LINEITEM.L_SHIPINSTRUCT = 'TAKE BACK RETURN' AND
LINEITEM.L_SHIPMODE = 'MAIL';

CREATE STATISTICS LINEITEM_L_LINENUMBER
    ON LINEITEM(L_LINENUMBER) 
WHERE LINEITEM.L_RETURNFLAG = 'N' AND
LINEITEM.L_LINESTATUS = 'O' AND
LINEITEM.L_SHIPINSTRUCT = 'TAKE BACK RETURN' AND
LINEITEM.L_SHIPMODE = 'MAIL';

CREATE STATISTICS LINEITEM_L_PARTKEY
    ON LINEITEM(L_PARTKEY) 
WHERE LINEITEM.L_RETURNFLAG = 'N' AND
LINEITEM.L_LINESTATUS = 'O' AND
LINEITEM.L_SHIPINSTRUCT = 'TAKE BACK RETURN' AND
LINEITEM.L_SHIPMODE = 'MAIL';

CREATE STATISTICS LINEITEM_ALL
    ON LINEITEM(L_ORDERKEY,L_LINENUMBER,L_PARTKEY) 
WHERE LINEITEM.L_RETURNFLAG = 'N' AND
LINEITEM.L_LINESTATUS = 'O' AND
LINEITEM.L_SHIPINSTRUCT = 'TAKE BACK RETURN' AND
LINEITEM.L_SHIPMODE = 'MAIL';

CREATE STATISTICS PART_P_PARTKEY
    ON PART(P_PARTKEY) 
WHERE PART.P_MFGR = 'Manufacturer#1';



