SELECT DISTINCT PARTSUPP.PS_PARTKEY, PARTSUPP.PS_SUPPKEY
FROM PARTSUPP, PART, SUPPLIER, NATION
WHERE  
PARTSUPP.PS_PARTKEY = PART.P_PARTKEY AND
PART.P_MFGR = 'Manufacturer#1' AND
PART.P_BRAND = 'Brand#13' AND
PARTSUPP.PS_SUPPKEY = SUPPLIER.S_SUPPKEY AND
SUPPLIER.S_ACCTBAL > 2000 AND
SUPPLIER.S_NATIONKEY = NATION.N_NATIONKEY AND
NATION.N_NAME LIKE 'UNITED%';
