SELECT DISTINCT PART.P_PARTKEY, NATION.N_NATIONKEY
FROM ORDERS, PART, CUSTOMER, NATION
WHERE ORDERS.O_CUSTKEY=CUSTOMER.C_CUSTKEY AND 
PART.P_RETAILPRICE=ORDERS.O_TOTALPRICE AND
PART.P_MFGR='Manufacturer#1' AND
NATION.N_NATIONKEY = CUSTOMER.C_NATIONKEY;